# ===============================================
# 1. DATABASE CONFIGURATIE (POSTGRESQL OP NEON)
# ===============================================

spring.datasource.url=jdbc:postgresql://ep-super-violet-aedl8i4n-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vMVSiJc4uCO8

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================================
# 2. NO-FOLDER STRUCTURE (ALLES IN DE MAIN MAP)
# ===============================================

spring.thymeleaf.prefix=classpath:/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

spring.web.resources.static-locations=classpath:/


# ===============================================
# 3. SERVER EN LOGGING
# ===============================================

server.port=8081

logging.level.org.springframework.security=INFO
